# Generated by Django 3.2.9 on 2023-08-17 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 12, 46, 57, 678222), verbose_name='date published '),
        ),
    ]
