# Generated by Django 3.2.9 on 2023-08-17 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 15, 30, 41, 125212), verbose_name='date published '),
        ),
    ]
