# Generated by Django 3.2.9 on 2023-08-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20230822_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 11, 58, 48, 175641), verbose_name='date published'),
        ),
    ]
