# Generated by Django 3.2.9 on 2023-08-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20230822_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 12, 10, 46, 420272), verbose_name='date published'),
        ),
    ]
