# Generated by Django 3.2.9 on 2023-08-24 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 13, 44, 42, 674917), verbose_name='date published'),
        ),
    ]
