# Generated by Django 3.2.9 on 2023-08-24 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20230824_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 15, 13, 11, 20419), verbose_name='date published'),
        ),
    ]
