# Generated by Django 3.2.9 on 2023-08-24 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_auto_20230824_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 16, 14, 38, 173801), verbose_name='date published'),
        ),
    ]
