# Generated by Django 3.2.9 on 2023-09-04 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 8, 7, 33, 596647), verbose_name='date published'),
        ),
    ]
