# Generated by Django 3.2.9 on 2023-09-04 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_alter_tutorial_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 8, 17, 58, 830512), verbose_name='date published'),
        ),
    ]
